# Change these first
owner: CitybookServicesLTD # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Citybook Help
    url: https://help.citybook.co.il
  - name: FortiGate Ping
    url: https://fg.mi.citybook.co.il
    check: "ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://citybook.co.il/images/CB-logo.png
  name: Citybook Status
  introTitle: "**Citybook** internal IT status page, powered by GitHub."
  introMessage: This is the Citybook status page which uses **real-time** data monitored by GitHub Actions.<br><br>In case one of the sites is down, it will automatically create a Github Issue, and will send a Teams Message to the [Status Down Channel](https://teams.microsoft.com/l/channel/19%3Adada7853c0c54bc3a533709479637264%40thread.tacv2/Status%20Down?groupId=86fe4482-d1f1-43b1-a039-566769c3bccf&tenantId=bbfeea83-3c0f-4fcc-838e-a0848f3fcb93&ngc=true).
  navbar:
    - title: Status
      href: /
    - title: FortiGate
      href: https://fg.mi.citybook.co.il
    - title: Issues
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more.
# See https://upptime.js.org/docs/configuration
