# Change these first
owner: CitybookServicesLTD # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Citybook Help
    url: https://help.citybook.co.il
  - name: FortiGate Ping
    url: https://fg.mi.citybook.co.il
    check: "ping"
  - name: Notification Test
    url: https://sdfgklh78459eiwerftg.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://citybook.co.il/images/CB-logo.png
  name: Citybook Status
  introTitle: "**Citybook** status page, powered by GitHub."
  introMessage: This is the Citybook status page which uses **real-time** data from our [GitHub repository](https://github.com/CitybookServicesLTD/status-monitor). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
